DB_ST.Web/Controllers/ClaseController.cs
using DB_ST.Domain;
using DB_ST.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using DB_ST.Web.Models.Extensions;

namespace DB_ST.Web.Controllers
{
    [Authorize(Roles = Rols.Director)]
    public class ClaseController : Controller
    {
        IMasterService<Clase> _service;
        IMasterService<Asignatura> _serviceAsignatura;
        IMasterService<AnioEscolar> _serviceAnio;
        private IMasterService<Seccion> _serviceSeccion;
        private IMasterService<Grado> _serviceGrado;
        private IMasterService<Empleado> _sEmpleado;
        // GET: Clase

        public ClaseController(
            IMasterService<Clase> service,
            IMasterService<Asignatura> serviceAsignatura,
            IMasterService<AnioEscolar> serviceAnio,
            IMasterService<Seccion> serviceSeccion,
            IMasterService<Grado> serviceGrado,
            IMasterService<Empleado> sEmpleado)
        {
            _service = service;
            _serviceAsignatura = serviceAsignatura;
            _serviceAnio = serviceAnio;
            _serviceSeccion = serviceSeccion;
            _serviceGrado = serviceGrado;
            _sEmpleado = sEmpleado;
        }

        public ActionResult Index(string SearchCriteria,int? seccionId, bool verDisabled = false)
        {
            ViewBag.VerDisabled = verDisabled/*.ToString().ToLower()*/;
            ViewBag.VerDisabledString = verDisabled.ToString().ToLower();

            ViewBag.Titulo = "Clases";

            SelectList anioEscolars = new SelectList(_serviceAnio.GetAll(), "AnioEscolarId", "Anio");
            var anioEscolarSelectedId = _serviceAnio.Find(x => x.Anio.Equals(DateTime.Now.Year.ToString())).FirstOrDefault().AnioEscolarId;
            SelectListItem anioEscolarSelected = anioEscolars.FirstOrDefault(x => x.Value == anioEscolarSelectedId.ToString());
            anioEscolars = new SelectList(_serviceAnio.GetAll(), "AnioEscolarId", "Anio", anioEscolarSelected);

            SelectList grados = new SelectList(_serviceGrado.GetAll(), "GradoId", "Nombre");

            var seccionesList = _serviceSeccion.Find(x => x.AnioEscolar.Anio.Equals(DateTime.Now.Year.ToString()));
            SelectList secciones = new SelectList(seccionesList, "SeccionId", "Nombre");

            if (seccionId != null)
            {
                var gradoSelectedId = _serviceSeccion.GetById(seccionId).GradoId;
                SelectListItem gradoSelected = grados.FirstOrDefault(x => x.Value == gradoSelectedId.ToString());
                grados = new SelectList(_serviceGrado.GetAll(), "GradoId", "Nombre", gradoSelected);

                SelectListItem seccionSelected = secciones.FirstOrDefault(
                    x => x.Value == seccionId.ToString());
                secciones = new SelectList(seccionesList.ToList().FindAll(x=>x.GradoId==gradoSelectedId), "SeccionId", "Nombre",seccionSelected);
            }

            ViewBag.AnioEscolars = anioEscolars;
            ViewBag.Grados = grados;
            ViewBag.Secciones = secciones;

            if (string.IsNullOrEmpty(SearchCriteria))
                SearchCriteria = "";

            var lista = _service.Find(
                        m => m.Nombre.Contains(SearchCriteria) && m.IsHabilitado == true,
                        m => m.Asignatura
                    );

            return Request.IsAjaxRequest() ? (ActionResult)PartialView("_Index", lista) : View(lista);
        }

        public ActionResult GetBySeccionId(int? seccionId, bool verDisabled=false)
        {
            IEnumerable<Clase> clases;

            clases = _service.Find(s => s.SeccionId == seccionId, x => x.Empleado, x => x.Asignatura);

            IEnumerable<Clase> clasesHabilitadas = clases.ToList().FindAll(x => x.IsHabilitado);

            //if (!verDisabled)
            //    clases = clasesHabilitadas;

            return PartialView("_GetBySeccionId", verDisabled? clases:clasesHabilitadas);
        }

        [AllowAnonymous]
        public JsonResult GetByAsignaturaId(int? asignaturaId, int? anioEscolarId)
        {
            List<Clase> lista = new List<Clase>();
            if (asignaturaId != null)
            {
                lista = _service.Find
                (
                    s => s.AsignaturaId == asignaturaId.Value,
                    x => x.Seccion
                ).ToList();

                if (User.IsInRole("docente"))
                {
                    var userEmpleadoId = int.Parse(User.Identity.GetUserEmpleadoId());
                    lista = lista.FindAll(x => x.EmpleadoId == userEmpleadoId);
                }
            }

            if (anioEscolarId != null)
                lista = lista.FindAll(x => x.Seccion.AnioEscolarId == anioEscolarId);
            else
                lista = lista.FindAll(x => x.Seccion.AnioEscolar.Anio.Equals(DateTime.Now.Year.ToString()));

            return Json(lista, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create(int? seccionId)
        {
            ViewBag.Titulo = "Registrar";

            ViewBag.Asignaturas = GetAsignaturasList();
            ViewBag.Anios = GetAniosList();
            ViewBag.Docentes = GetDocentesList();

            if (seccionId != null)
                return View(new Clase { SeccionId = seccionId.Value });
            else
                return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Create(Clase model)
        {
            Validar(model);
            if (ModelState.IsValid)
            {
                model.IsHabilitado = true;
                _service.Add(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            ViewBag.Titulo = "Modificar";

            ViewBag.Asignaturas = GetAsignaturasList();
            ViewBag.Anios = GetAniosList();
            ViewBag.Docentes = GetDocentesList();

            var model = _service.GetById(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Clase model)
        {
            Validar(model);
            if (ModelState.IsValid)
            {
                _service.Edit(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Details(int id)
        {
            ViewBag.Titulo = "Detalles";
            var model = _service.GetById(id);
            return View(model);
        }

        public ActionResult Disable(int? id)
        {
            ViewBag.Titulo = "Deshabilitar/Habilitar Clase";
            var model = _service.GetById(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Disable(int id)
        {
            Clase model = _service.GetById(id);
            if (ModelState.IsValid)
            {
                if (model.IsHabilitado == true)
                    model.IsHabilitado = false;
                else
                    model.IsHabilitado = true;
                _service.Edit(model);
                return RedirectToAction("Index");
            }
            return View();
        }

        public SelectList GetAsignaturasList()
        {
            return new SelectList(_serviceAsignatura.GetAll(), "AsignaturaId", "Nombre");
        }
        public SelectList GetDocentesList()
        {
            return new SelectList(_sEmpleado.Find(x=>x.TipoEmpleado.NombreTipoEmpleado.ToLower()=="docente"), "EmpleadoId", "FullName");
        }

        public SelectList GetAniosList()
        {
            return new SelectList(_serviceAnio.GetAll(), "AnioEscolarId", "Anio");
        }
        
        public ActionResult Delete(int id)
        {
            if (ModelState.IsValid)
            {
                _service.Remove(id);
            }
            return RedirectToAction("Index");
        }


        //Validaciones///////////////////////////////////////////////////////////////
        private void Validar(Clase clase)
        {
            ModelState.Clear();
            if (_service.Find(x => x.Nombre == clase.Nombre
                                    && x.ClaseId!=clase.ClaseId).Any())
                    ModelState.AddModelError("Nombre", "Ya Existe");
            if (string.IsNullOrEmpty(clase.Nombre))
                ModelState.AddModelError("Nombre", "Campo requerido");
        }
    }
}

DB_ST.Web/Controllers/SesionController.cs
using DB_ST.Domain;
using DB_ST.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DB_ST.Web.Controllers
{
    [Authorize(Roles = Rols.Director)]
    public class SesionController : Controller
    {
        private IMasterService<Sesion> _serviceSesion;
        private IMasterService<Clase> _serviceClase;
        private IMasterService<Grado> _serviceGrado;
        //private IMasterService<Asignatura> _serviceAsignatura;
        private IMasterService<Seccion> _serviceSeccion;
        private IMasterService<Horario> _serviceHorario;
        //private IMasterService<Estudiante> _serviceEstudiante;

        public SesionController
            (
            IMasterService<Sesion> serviceSesion,
            IMasterService<Clase> serviceClase,
            IMasterService<Grado> serviceGrado,
            //IMasterService<Asignatura> serviceAsignatura,
            IMasterService<Seccion> serviceSeccion,
            IMasterService<Horario> serviceHorario
            //IMasterService<Estudiante> serviceEstudiante
            )
        {
            _serviceSesion = serviceSesion;
            _serviceClase = serviceClase;
            _serviceGrado = serviceGrado;
            //_serviceAsignatura = serviceAsignatura;
            _serviceSeccion = serviceSeccion;
            _serviceHorario = serviceHorario;
            //_serviceEstudiante = serviceEstudiante;
        }
        // GET: HorarioEstudiante
        public ActionResult Index()
        {
            ViewBag.Titulo = "Clases";

            ViewBag.Secciones = _serviceSeccion.GetAll();
            ViewBag.Grados = _serviceGrado.GetAll();

            return View("Index");
        }

        //A C-Sesion
        public ActionResult GetByClaseId(int claseId)
        {
            var sesiones = _serviceSesion.Find(s => s.ClaseId == claseId, x => x.Clase, x=>x.Clase.Seccion,x=>x.Horario);
            var clase = _serviceClase.GetById(claseId);
            var seccion = _serviceSeccion.GetById(clase.SeccionId);
            var grado = _serviceGrado.GetById(seccion.GradoId);
            @ViewBag.Titulo = "Sesiones para '" + clase.Nombre + "' (" + grado.Nombre + "-" + seccion.Nombre + ")";
            @ViewBag.ClaseId = clase.ClaseId;
            return View(sesiones);
        }

        public void llenarCombos()
        {
            ViewBag.Horarios = new SelectList(_serviceHorario.GetAll(),"HorarioId", "Full");
        }
        //A C-Sesion
        public ActionResult Create(int claseId)
        {
            llenarCombos();
            ViewBag.Titulo = "Registrar";
            return View(new Sesion
            {
                ClaseId = claseId 
                //HoraInicio =DateTime.Now.Date,
                //HoraFin = DateTime.Now.Date
            });

            //if (claseId != null)
            //    return View(new Sesion { ClaseId = claseId.Value });
            //else
            //    return null;
        }

        private Clase GetClaseCompleta(int claseId)
        {
            return _serviceClase.Find(x => x.ClaseId == claseId, x => x.Asignatura).FirstOrDefault();
        }

        //A C-Sesion
        [HttpPost]
        public ActionResult Create(Sesion model)
        {
            Validar(model);

            if (ModelState.IsValid)
            {
                _serviceSesion.Add(model);
                return RedirectToAction("GetByClaseId", new { claseId=model.ClaseId});
            }
            llenarCombos();
            return View(model);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = _serviceSesion.GetById(id);

            if (model == null)
            {
                return HttpNotFound();
            }
            llenarCombos();
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Sesion model)
        {
            Validar(model);
            if (ModelState.IsValid)
            {
                _serviceSesion.Edit(model);
                return RedirectToAction("GetByClaseId", new { claseId = model.ClaseId });
            }
            llenarCombos();
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            var model = GetSesionCompleta(id);

            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        private Sesion GetSesionCompleta(int id)
        {
            return _serviceSesion.Find(x => x.SesionId == id, x => x.Clase, x => x.Horario).FirstOrDefault();
        }

        [HttpPost]
        public ActionResult Delete(Sesion model)
        {
            if (ModelState.IsValid)
            {
                var claId= model.ClaseId;
                _serviceSesion.Remove(model.SesionId);
                return RedirectToAction("GetByClaseId", new { claseId = claId });
            }
            return View(model);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = GetSesionCompleta(id.Value);

            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        //validaciones/////////////////
        private void Validar(Sesion sesion)
        {
            ModelState.Clear();
            var clase = GetClaseCompleta(sesion.ClaseId);

            var sesionesSolapadas = _serviceSesion.Find(x => x.Dia == sesion.Dia
                                    && x.HorarioId == sesion.HorarioId
                                    && x.Clase.SeccionId == clase.SeccionId
                                    && x.SesionId != sesion.SesionId,
                                    x=>x.Clase.Asignatura);
            if (sesionesSolapadas.Any())
                ModelState.AddModelError("HorarioId", "Sesión solapada con " + sesionesSolapadas.FirstOrDefault().Clase.FullAsignaturaClase);
            if (string.IsNullOrEmpty(sesion.Dia.ToString()))
                ModelState.AddModelError("Dia", "Campo requerido");
            if (sesion.HorarioId<1)
                ModelState.AddModelError("HoraInicio", "Campo requerido");
        }


    }
}

DB_ST.Web/Views/Clase/Create.cshtml
@model DB_ST.Domain.Clase

@{
    ViewBag.Title = ViewBag.Titulo;
}

<h2>@ViewBag.Titulo</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Clase</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Capacidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capacidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Capacidad, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.IsHabilitado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsHabilitado)
                    @Html.ValidationMessageFor(model => model.IsHabilitado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.AsignaturaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.AsignaturaId, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.AsignaturaId,
                    ViewBag.Asignaturas as SelectList,
                    "[Asignatura]",
                    new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AsignaturaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmpleadoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.AsignaturaId, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.EmpleadoId,
                    ViewBag.Docentes as SelectList,
                    "[Docente]",
                    new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmpleadoId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DB_ST.Web/Views/Clase/Details.cshtml
@model DB_ST.Domain.Clase

@{
    ViewBag.Title = ViewBag.Titulo;
}

<h2>@ViewBag.Titulo</h2>

<div>
    <h4>Clase</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.IsHabilitado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsHabilitado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AsignaturaId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Asignatura.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmpleadoId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empleado.FullName)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ClaseId }) |
    @Html.ActionLink("Volver a la lista", "Index")
</p>

DB_ST.Web/Views/Clase/Disable.cshtml
@model DB_ST.Domain.Clase

@{
    ViewBag.Title = @ViewBag.Titulo;
}

<h2>@ViewBag.Titulo</h2>

@if (Model.IsHabilitado == true)
{
    <h3>¿Desea deshabilitar esta clase?</h3>
}
else
{
    <h3>¿Desea habilitar esta clase?</h3>
}

<div>
    <h4>Clase</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.IsHabilitado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsHabilitado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AsignaturaId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AsignaturaId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmpleadoId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empleado.FullName)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @*<input type="submit" value="Delete" class="btn btn-default" />*@ 
            @if (Model.IsHabilitado == true)
            {
                <button class="btn btn-danger">Deshabilitar</button>
            }
            else
            {
                <button class="btn btn-danger">Habilitar</button>
            }  
            |
            @Html.ActionLink("Volver a la lista", "Index")
        </div>
    }
</div>

DB_ST.Web/Views/Clase/Edit.cshtml
@model DB_ST.Domain.Clase

@{
    ViewBag.Title = ViewBag.Titulo;
}

<h2>@ViewBag.Titulo</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Clase</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ClaseId)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Capacidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capacidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Capacidad, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.IsHabilitado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsHabilitado)
                    @Html.ValidationMessageFor(model => model.IsHabilitado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@
        @Html.HiddenFor(model => model.IsHabilitado)
        @Html.HiddenFor(model => model.SeccionId)

        <div class="form-group">
            @Html.LabelFor(model => model.AsignaturaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.AsignaturaId, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.AsignaturaId,
                    ViewBag.Asignaturas as SelectList,
                    "[Asignatura]",
                    new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AsignaturaId, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.EmpleadoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.AsignaturaId, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.EmpleadoId,
                    ViewBag.Docentes as SelectList,
                    "[Docente]",
                    new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmpleadoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DB_ST.Web/Views/Clase/_GetBySeccionId.cshtml
@model IEnumerable<DB_ST.Domain.Clase>

<p>
    <a href="#" class="BtnCreateSesion">Crear Nueva</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsHabilitado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AsignaturaId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmpleadoId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsHabilitado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Asignatura.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Empleado.FullName)
        </td>
        <td>
            @Html.ActionLink("Adm. Sesiones", "GetByClaseId","Sesion", new { claseid = item.ClaseId },null) |
            @Html.ActionLink("Edit", "Edit", new { id=item.ClaseId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ClaseId }) |
            @Html.ActionLink(item.IsHabilitado? "Disable":"Enable", "Disable", new { id=item.ClaseId })
        </td>
    </tr>
}

</table>

<script type="text/javascript">
        $(document).ready(function () {
            $(".BtnCreateSesion").click(function () {
                $('.BtnCreateSesion').attr('href', '/Clase/Create?seccionId=' + $("#SeccionId").val());
            });
        });
</script>

DB_ST.Web/Views/Clase/_Index.cshtml
@model IEnumerable<DB_ST.Domain.Clase>

<p>
    @Html.ActionLink("Registrar nuevo", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsHabilitado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AsignaturaId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsHabilitado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Asignatura.Nombre)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.ClaseId }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.ClaseId }) |
            @Html.ActionLink("Desactivar", "Disable", new { id = item.ClaseId }) @*|
            @Html.ActionLink("Delete", "Delete", new { id=item.ClaseId })*@
        </td>
    </tr>
}

</table>