DB_ST.Web/Controllers/ApoderadoController.cs
using DB_ST.Domain;
using DB_ST.Service;
using DB_ST.Web.Models;
using DB_ST.Web.Validators;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DB_ST.Web.Controllers
{
    [Authorize(Roles = Rols.Secretario)]
    public class ApoderadoController : Controller
    {
        IMasterService<Apoderado> _service;
        private ApplicationDbContext _context = new ApplicationDbContext();

        public ApoderadoController(IMasterService<Apoderado> service)
        {
            _service = service;
        }

        //GET: Apoderado
        public ActionResult Index(string SearchCriteria, int? page)
        {
            if (string.IsNullOrEmpty(SearchCriteria))
                SearchCriteria = "";

            var lista = _service.Find(
                        m => m.DNI.Contains(SearchCriteria)
                        //, x => x.Estudiante, x => x.Seccion, x => x.Grado, x => x.AnioEscolar
                    );

            ViewBag.SearchCriteria = SearchCriteria;

            var pageIndex = page ?? 1;
            lista = lista.OrderBy(p => p.Apellidos).ToPagedList(pageIndex, Configuraciones.defaultPageSize);

            return Request.IsAjaxRequest() ? (ActionResult)PartialView("_Index", lista) : View(lista);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Apoderado apoderado)
        {
            Validar(apoderado);

            if (ModelState.IsValid)
            {
                _service.Add(apoderado);
                try
                {

                    var userStore = new UserStore<ApplicationUser>(_context);
                    var userManager = new UserManager<ApplicationUser>(userStore);

                    //var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();//primero se migra la base de datos y se copias esta parte de codigo
                    var user = new ApplicationUser
                    {
                        UserName = apoderado.Email,
                        Email = apoderado.Email,
                        EmpleadoId = apoderado.ApoderadoId
                    };
                    var result = userManager.Create(user, "St2017*");
                    _context.Roles.AddOrUpdate(r => r.Name, new IdentityRole() { Name=Rols.Apoderado });
                    _context.SaveChanges();
                    userManager.AddToRole(user.Id, Rols.Apoderado);

                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine("ERROR: " + ex.Message);
                }
                return RedirectToAction("Index");
            }
            return View(apoderado);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = _service.GetById(id);

            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Apoderado apoderado)
        {
            Validar(apoderado);
            if (ModelState.IsValid)
            {
                _service.Edit(apoderado);
                return RedirectToAction("Index");
            }
            return View(apoderado);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = _service.GetById(id);

            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(Apoderado apoderado)
        {
            if (ModelState.IsValid)
            {
                _service.Remove(apoderado.ApoderadoId);
                return RedirectToAction("Index");
            }
            return View(apoderado);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = _service.GetById(id);

            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        //Validaciones///////////////////////////////////////////////////////////////
        private void Validar(Apoderado apoderado)
        {
            ModelState.Clear();
            if (!string.IsNullOrEmpty(apoderado.DNI) && _service.Find(x => x.DNI == apoderado.DNI 
                                                                        && x.ApoderadoId!=apoderado.ApoderadoId).Any())
                ModelState.AddModelError("DNI", "Campo repetido");
            

            if (string.IsNullOrEmpty(apoderado.Nombres))
                ModelState.AddModelError("Nombres", "Campo requerido");
            if (string.IsNullOrEmpty(apoderado.Apellidos))
                ModelState.AddModelError("Apellidos", "Campo requerido");
            if (!string.IsNullOrEmpty(apoderado.DNI) && !Validator.IsDNI(apoderado.DNI))
                ModelState.AddModelError("DNI", "Inválido.");
            if (String.IsNullOrEmpty(apoderado.FechaNacimiento.ToString()))
                ModelState.AddModelError("FechaNacimiento", "Campo requerido");
            if (string.IsNullOrEmpty(apoderado.Celular))
                ModelState.AddModelError("Celular", "Campo requerido");
        }
    }
}

DB_ST.Web/Controllers/EstudianteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DB_ST.Domain;
using DB_ST.Service;
using System.Text.RegularExpressions;
using DB_ST.Web.Validators;
using PagedList;

namespace DB_ST.Web.Controllers
{
    [Authorize(Roles = Rols.Secretario)]
    public class EstudianteController : Controller
    {
        IMasterService<Estudiante> _service;
        //ubigeo
        IMasterService<Departamento> _serviceDep;
        IMasterService<Provincia> _servicePro;
        IMasterService<Distrito> _serviceDis;

        SelectList deps;
        SelectList pros;
        SelectList diss;

        public EstudianteController(IMasterService<Estudiante> service,
            IMasterService<Departamento> serviceDep,
            IMasterService<Provincia> servicePro,
            IMasterService<Distrito> serviceDis)
        {
            _service = service;

            _serviceDep = serviceDep;
            _servicePro = servicePro;
            _serviceDis = serviceDis;

            deps = new SelectList(_serviceDep.GetAll(), "DepartamentoId", "Nombre");
            pros = new SelectList(_servicePro.GetAll(), "ProvinciaId", "Nombre");
            diss = new SelectList(_serviceDis.GetAll(), "DistritoId", "Nombre");
        }

        // GET: Estudiante
        public ActionResult Index(string SearchCriteria, int? page)
        {
            //var datos = _service.GetEstudiantes(SearchCriteria);
            //return View(datos);

            ViewBag.Titulo = "Estudiantes";


            if (string.IsNullOrEmpty(SearchCriteria))
                SearchCriteria = "";

            var lista = _service.Find(
                        m => m.DNI.Contains(SearchCriteria) && m.Habilitado,m=> m.Distrito
                    );

            ViewBag.SearchCriteria = SearchCriteria;

            var pageIndex = page ?? 1;
            lista = lista.OrderBy(p => p.Apellidos).ToPagedList(pageIndex, Configuraciones.defaultPageSize);

            return Request.IsAjaxRequest() ? (ActionResult)PartialView("_Index", lista) : View(lista);
        }

        public ActionResult Create()
        {
            ViewBag.Deps = deps;
            ViewBag.Pros = pros;
            ViewBag.Diss = diss;

            ViewBag.Titulo = "Registrar";
            return View();
        }
        [HttpPost]
        public ActionResult Create(Estudiante estudiante)
        {
            Validar(estudiante);

            if (ModelState.IsValid)
            {
                estudiante.Habilitado = true;
                _service.Add(estudiante);
                return RedirectToAction("Index");
            }
            ViewBag.Deps = deps;
            ViewBag.Pros = pros;
            ViewBag.Diss = diss;

            return View(estudiante);
        }

        public ActionResult Edit(int id)
        {
            ViewBag.Deps = deps;
            ViewBag.Pros = pros;
            ViewBag.Diss = diss;

            ViewBag.Titulo = "Editar";
            var model = _service.GetById(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Estudiante estudiante)
        {
            Validar(estudiante);
            if (ModelState.IsValid)
            {
                _service.Edit(estudiante);
                return RedirectToAction("Index");
            }
            ViewBag.Deps = deps;
            ViewBag.Pros = pros;
            ViewBag.Diss = diss;
            return View(estudiante);
        }

        public ActionResult Details(int id)
        {
            ViewBag.Titulo = "Detalles";
            var model = _service.GetById(id);
            return View(model);
        }

        public ActionResult Disable(int? id)
        {
            ViewBag.Titulo = "Deshabilitar/Habilitar";
            var model = _service.GetById(id);
            return View(model);
        }
        [HttpPost]
        public ActionResult Disable(int id)
        {
            Estudiante estudiante= _service.GetById(id);
            if (ModelState.IsValid)
            {
                if (estudiante.Habilitado == true)
                    estudiante.Habilitado = false;
                else
                    estudiante.Habilitado = true;
                _service.Edit(estudiante);
                return RedirectToAction("Index");
            }
            return View();
        }
        //[HttpPost]
        //public ActionResult Disable(Estudiante estudiante)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        if(estudiante.Habilitado == true)
        //            estudiante.Habilitado = false;
        //        else
        //            estudiante.Habilitado = false;

        //        _service.Edit(estudiante);
        //        return RedirectToAction("Index");
        //    }
        //    return View();
        //}

        [HttpPost]
        public ActionResult Delete(Estudiante estudiante)
        {
            if (ModelState.IsValid)
            {
                //estudiante.Habilitado = false;
                _service.Remove(estudiante.EstudianteId);
                return RedirectToAction("Index");
            }
            return View();
        }
//----------------------------------------------------------------------------
        [AllowAnonymous]
        public JsonResult GetProvincias(int? id)
        {
            List<Provincia> lista;
            if (id != null)
                lista = _servicePro.Find(x => x.DepartamentoId == id).ToList();
            else
                lista = new List<Provincia>();

            return Json(lista, JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        public JsonResult GetDistritos(int? id)
        {
            List<Distrito> lista;
            if (id != null)
                lista = _serviceDis.Find(x => x.ProvinciaId == id).ToList();
            else
                lista = new List<Distrito>();

            return Json(lista, JsonRequestBehavior.AllowGet);
        }


        //Validaciones///////////////////////////////////////////////////////////////
        private void Validar(Estudiante estudiante)
        {
            ModelState.Clear();

            if (_service.Find(x => x.DNI == estudiante.DNI && x.EstudianteId!=estudiante.EstudianteId).Any())
                ModelState.AddModelError("DNI", "Campo repetido");
            if (string.IsNullOrEmpty(estudiante.Nombres))
                ModelState.AddModelError("Nombres", "Campo requerido");
            if (string.IsNullOrEmpty(estudiante.Apellidos))
                ModelState.AddModelError("Apellidos", "Campo requerido");
            if (!string.IsNullOrEmpty(estudiante.DNI) && !Validator.IsDNI(estudiante.DNI))
                ModelState.AddModelError("DNI", "Inválido.");
            if (string.IsNullOrEmpty(estudiante.FechaNacimiento.ToString()))
                ModelState.AddModelError("Naciemiento", "Campo requerido");
            if (string.IsNullOrEmpty(estudiante.Direccion))
                ModelState.AddModelError("Direccion", "Campo requerido");
        }
    }
}

DB_ST.Web/Views/Matricula/Create.cshtml
@model DB_ST.Domain.Matricula

@{
    ViewBag.Title = "Registrar";
}

<h2>@ViewBag.Title</h2>

<h4>Matricula</h4>
<hr />
@Html.Partial("_resultado")

@if (ViewBag.error==null)
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    
    <div class="row">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.MatriculaId)
            @Html.HiddenFor(m => m.FechaMatricula)

            <div class="form-horizontal">
                    <div class="form-horizontal ">
                        <div class="col-sm-12">
                            <div class="form-group">
                                @Html.LabelFor(model => model.TipoMatricula, htmlAttributes: new { @class = "control-label col-md-3" })
                                @Html.DisplayFor(model => model.TipoMatricula, new { htmlAttributes = new { @class = "form-control" } })
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.FechaMatricula, htmlAttributes: new { @class = "control-label col-md-3" })
                                @Html.DisplayFor(model => model.FechaMatricula, new { htmlAttributes = new { @class = "form-control" } })
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.MontoMatricula, htmlAttributes: new { @class = "control-label col-md-3" })
                                @Html.DisplayFor(model => model.MontoMatricula, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>

                        <div class="col-sm-12">
                            <div class="form-group row">
                                @Html.LabelFor(model => model.EstudianteId, htmlAttributes: new { @class = "control-label col-md-3" })
                                @Html.DropDownList("EstudianteId", ViewBag.Estudiantes as SelectList, "[Estudiante]", new { @class = "form-control select2" })
                                <a class="btn btn-success" href="@Url.Action("Create", "Estudiante")"><span class='glyphicon glyphicon-plus'>Agregar</span></a>
                            </div>

                            <div  id="TrasladoEntrante">
                            </div>     

                            <div class="form-group row">
                                @Html.LabelFor(model => model.ApoderadoId, htmlAttributes: new { @class = "control-label col-md-3" })
                                @Html.DropDownList("ApoderadoId", ViewBag.Apoderados as SelectList, "[Apoderado]", new { @class = "form-control select2" })
                                <a class="btn btn-success" href="@Url.Action("Create", "Apoderado")"><span class='glyphicon glyphicon-plus'>Agregar</span></a>
                            </div>
                        </div>

                        <div class="col-sm-12">
                            <div class="form-group">
                                @Html.LabelFor(model => model.GradoId, htmlAttributes: new { @class = "control-label col-md-3" })
                                @*<div class="col-md-9">*@
                                    @Html.DropDownListFor(model => model.GradoId, ViewBag.Grados as SelectList, "[Grado]", new { @class = "form-control select2", @id = "SelectGrado" })
                                    @*@Html.ValidationMessageFor(model => model.GradoId, "", new { @class = "text-danger" })*@
                                @*</div>*@
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.SeccionId, htmlAttributes: new { @class = "control-label col-md-3" })
                                @*<div class="col-md-9">*@

                                @Html.DropDownListFor(model => model.SeccionId, new SelectList(new List<DB_ST.Domain.Seccion>(),"SeccionId","Nombre"), "[Sección]", new { @class = "form-control select2", @id = "SelectSeccion" })
                                    @*<select id="SelectSeccion" class="form-control select2">
                                        <option>[Sección]</option>
                                    </select>*@
                                    @*@Html.ValidationMessageFor(model => model.SeccionId, "", new { @class = "text-danger" })*@
                                @*</div>*@
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.NumeroVoucher, htmlAttributes: new { @class = "control-label col-md-3" })
                                @*<div class="col-md-9">*@
                                @Html.EditorFor(model => model.NumeroVoucher, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NumeroVoucher, "", new { @class = "text-danger" })
                                @*</div>*@
                            </div>

                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-6 col-md-8">
                                <input type="submit" value="Registrar" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
            </div>
        }


        <div id="StudentName" class="col-sm-4">
        </div>

    </div>

    <div>
        @Html.ActionLink("Volver a la lista", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")

        <script>
            $(".select2").select2();

        $(function () {
            $('#FechaMatricula').datepicker(
            {
                format: "dd/mm/yyyy"
            });
        });
        </script>


        <script type="text/javascript">

        $(function () {
            cargarSecciones();
            $("#SelectGrado").change(function () {
                cargarSecciones();
            });

            $("#EstudianteId").change(function () {
                cargarTraslado();
                cargarGrados();
            });


            $("#SelectSeccion").change(function () {
                $("#SeccionId").val($("#SelectSeccion").val());
            });

            //$(document).on("click",/* "#EstudianteNombre"*/ "#btnBuscarEstudiante", function (e) {
            //    setTimeout(cargarTraslado, 500);
            //});
        });

        function cargarTraslado() {
            $.ajax({
                type: 'Get',
                url: '@Url.Action("GetTraslado")' + '/?id=' + $("#EstudianteId").val(),
                dataType: 'html',
                success: function (data) {
                    var trasladoDivSelector="#TrasladoEntrante";
                    $(trasladoDivSelector).html(data);
                    if ($(trasladoDivSelector).html() != "" && !$(trasladoDivSelector).hasClass("form-group"))
                        $(trasladoDivSelector).addClass("form-group");
                    else
                        $(trasladoDivSelector).removeClass("form-group");
                        
                },
                error: function (ex) {
                    //alert('Error al cargar el formulario de traslado' + ex);
                }
            });
        }


        function cargarGrados()
        {
            $.get("/Matricula/GetGradosByEstudiante", { estudianteId: $("#EstudianteId").val() }, function (data) {
                $("#SelectGrado").empty();
                $("#SelectGrado").append("<option>[Grado]</option>")
                $.each(data, function (index, row) {
                    $("#SelectGrado").append("<option value='" + row.GradoId + "'>" + row.Nombre + "</option>")
                });
            });
        }

        function cargarSecciones() {
            $.get("/Matricula/GetSeccionesByGrado", { id: $("#SelectGrado").val(), soloConCupos:true }, function (data) {
                $("#SelectSeccion").empty();
                $("#SelectSeccion").append("<option>[Sección]</option>")
                $.each(data, function (index, row) {
                    $("#SelectSeccion").append("<option value='" + row.SeccionId + "'>" + row.Nombre + "</option>")
                });
            });
        }
        </script>
    }



}

DB_ST.Web/Views/Matricula/Delete.cshtml
@model DB_ST.Domain.Matricula

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Se eliminarán todas las notas del estudiante que pertenezcan a esta matrícula, ¿Estás seguro?</h3>
<div>
    <h4>Matricula</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FechaMatricula)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaMatricula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estudiante)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Estudiante.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apoderado)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Apoderado.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnioEscolar)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AnioEscolar.Anio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grado)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Grado.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Seccion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Seccion.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoMatricula)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TipoMatricula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MontoMatricula)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MontoMatricula)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x=>x.MatriculaId)
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Volver a la lista", "Index")
        </div>
    }
</div>

DB_ST.Web/Views/Matricula/Details.cshtml
@model DB_ST.Domain.Matricula

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Matricula</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FechaMatricula)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaMatricula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estudiante)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Estudiante.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apoderado)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Apoderado.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnioEscolar)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AnioEscolar.Anio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grado)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Grado.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Seccion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Seccion.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoMatricula)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TipoMatricula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MontoMatricula)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MontoMatricula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoEstudiante)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EstadoEstudiante)
        </dd>

        @{
            if (Model.EstadoEstudiante == DB_ST.Domain.Enum.EstadoEstudiante.Trasladado)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.CodigoInsitucionOrigen)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.CodigoInsitucionOrigen)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.RazonTraslado)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.RazonTraslado)
                </dd>
            }
        }
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MatriculaId }) |
    @Html.ActionLink("Volver a la lista", "Index")
</p>

DB_ST.Web/Views/Matricula/Index.cshtml
@using PagedList;

@model PagedList<DB_ST.Domain.Matricula>

@{
    ViewBag.Title = "Matrículas";
}

<h2>@ViewBag.Title</h2>

@Html.Partial("_resultado")

<div class="col-sm-12">
    @using (Ajax.BeginForm("Index", new AjaxOptions()
    {
        UpdateTargetId = "search_result",
        HttpMethod = "Get",
        InsertionMode = InsertionMode.Replace
    }))
    {
        <div class="row alert alert-info">
            <div class="col-md-12">
                <div class="form-group col-md-4">
                    @Html.Label("Año Escolar")
                    @Html.DropDownList("AnioEscolarId", ViewBag.AnioEscolars as SelectList, "[No Filtrar]", new { @class = "form-control" })
                </div>

                <div class="form-group col-md-4">
                    @Html.Label("Grado")
                    @Html.DropDownList("GradoId", ViewBag.Grados as SelectList, "[No Filtrar]", new { @class = "form-control" })
                </div>

                <div class="form-group col-md-4">
                    @Html.Label("Sección")
                    @Html.DropDownList("SeccionId", ViewBag.Secciones as SelectList, "[No Filtrar]", new { @class = "form-control" })
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group col-md-4">
                    @Html.Label("SearchCriteria", "DNI/Nombres de estudiante") <br />
                    @Html.TextBox("SearchCriteria", null, new { @class = "form-control" })
                </div>
                <div class="col-md-4"><br />
                    <button class="btn btn-danger">Buscar matrícula</button>
                </div>
            </div>
        </div>

    }

    <br />
    <div id="search_result">
        @Html.Partial("_Index", Model)
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        var seccionSelector = "#SeccionId";

        $("#GradoId,#AnioEscolarId").change(function () {
            cargarSecciones();
        });
        function cargarSecciones() {
            $.get("/Matricula/GetSeccionesByGrado",
                {
                    id: $("#GradoId").val(),
                    anioEscolarId: $("#AnioEscolarId").val()
                }
                , function (data) {
                $(seccionSelector).empty();
                $(seccionSelector).append("<option>[No Filtrar]</option>")
                $.each(data, function (index, row) {
                    $(seccionSelector).append("<option value='" + row.SeccionId + "'>" + row.Nombre + "</option>")
                });
            });
        }
    </script>
}

DB_ST.Web/Views/Matricula/_Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<DB_ST.Domain.Matricula>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@


@*<div class="row" style="margin-top:20px;padding-left:20px;">
    @Html.ActionLink("Create New", "Create")
</div>*@


@Html.ActionLink("Registrar nueva", "Create")

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().AnioEscolar)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Estudiante.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Estudiante.DNI)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Grado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Seccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().FechaMatricula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().TipoMatricula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().MontoMatricula)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AnioEscolar.Anio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estudiante.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estudiante.DNI)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grado.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Seccion.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaMatricula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoMatricula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MontoMatricula)
            </td>
            <td>
                @Html.ActionLink("Detalles", "Details", new { id = item.MatriculaId }) |
                @Html.ActionLink("Eliminar", "Delete", new { id = item.MatriculaId })
            </td>
        </tr>
    }

</table>


@Html.PagedListPager(Model, page => Url.Action("Index",
    new
    {
        page,
        SearchCriteria=ViewBag.SearchCriteria,
        AnioEscolarId = ViewBag.AnioEscolarId,
        GradoId = ViewBag.GradoId,
        SeccionId = ViewBag.SeccionId
    })
    ,
    PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions()
    {
        UpdateTargetId = "search_result",
        HttpMethod = "Get",
        InsertionMode = InsertionMode.Replace
    })
    )